import sys
import os
import random
import time
import datetime
import subprocess
q = "Enter digit number generates password."
c = "Do you Continue[Y/N]?"
s = "Enter times generates passwords."
b = "It will finish after digit number seconds you specify."
p = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","t","s","t","u","v","w","x","y","z","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","0","1","2","3","4","5","6","7","8","9"]
dt_now = datetime.datetime.now()
dt_now = str(dt_now)
def blockPrint():
    sys.stdout = open(os.devnull, 'w')
def enablePrint():
    sys.stdout = sys.__stdout__
f = open("index.html",'a+')
sys.stdout = f
subprocess.run('xdg-open index.html',shell=True)
f.write("<!DOCtype html>")
f.flush()
f.write("<head>")
f.flush()
f.write("<title>Password Maker</title>")
f.flush()
f.write("<style>p{border: solid 0.5px #000;}</style>")
f.flush()
f.write("<script>")
f.flush()
f.write("const timer = 10000")
f.flush()
f.write("\n")
f.flush()
f.write("window.addEventListener('load',function(){setInterval('location.reload()',timer);});")
f.flush()
f.write("\n")
f.flush()
f.write("</script>")
f.flush()
f.write("\n")
f.flush()
f.write("</head>")
f.flush()
f.write("\n")
f.flush()
f.write("<body>")
f.flush()
f.write("\n")
f.flush()
blockPrint()
f.write("<br>")
print(q)
f.write("<br>")
enablePrint()
f.write("<h1>Password list</h1>")
f.flush()
f.write("\n")
f.flush()
f.write(dt_now)
f.flush()
x=8
f.write("\n")
f.flush()
blockPrint()
print(s)
enablePrint()
y=16
f.write("<table>")
f.flush()
f.write("\n")
f.flush()
f.write("<tr>")
f.flush()
f.write("\n")
f.flush()
f.write("<td>")
f.flush()
f.write("\n")
f.flush()
f.write("<p>")
f.flush()
f.write("\n")
f.flush()
for k in range(int(y)):
  f.write("<br>")
  f.flush()
  for i in range(int(x)):
    f.write(random.choice(p))
    f.flush()
f.write("</td>")
f.flush()
f.write("\n")
f.flush()
f.write("</tr>")
f.flush()
f.write("\n")
f.flush()
blockPrint()
print("<br>"+c)
print("<br>")
enablePrint()
answer="Y"
f.write("\n")
f.flush()
while answer == "Y":
    for j in range(1):
        blockPrint()
        print(q)
        print("<br>")
        enablePrint()
        x=8
        blockPrint()
        print(s)
        enablePrint()
        y=16
        f.write("<p>")
        f.flush()
        f.write("</p>")
        f.flush()
        f.write("<tr>")
        f.flush()
        f.write("<td>")
        f.flush()
        f.write("<p>")
        f.flush()
        for k in range(int(y)):
          f.write("<br>")
          f.flush()
          for i in range(int(x)):
            f.write(random.choice(p))
            f.flush()
        f.write("</p>")
        f.flush()
        f.write("</p>")
        f.flush()
        f.write("</td>")
        f.flush()
        f.write("</tr>")
        f.flush()
        f.write("</table>")
        f.flush()
        blockPrint()
        print("<br>"+c)
        enablePrint()
        answer="N"
if answer == "N":
    blockPrint()
    print("<br>"+b)
    enablePrint()
    f.write("\n")
    f.flush()
    a=1
    f.write("</body>")
    f.flush()
    f.write("\n")
    f.flush()
    f.write("</html>")
    f.flush()
    time.sleep(int(a))
f.close()
