name: Password Maker for Web 2

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  pytest:
    name: Run tests with action-sample
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'auto rebuilding site')"
    steps:
      - uses: actions/checkout@v2
        with:
         token: "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"
         ref: "master"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Build
        run: |
          make html
      - name: Get Python version
        run: |
          python -V
      - name: Run Python
        run: |
          python PasswordMakerForWeb.py
      - name: Deploy Configuration
        run: |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.MY_ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: Push
        env:
          GITHUB_USER: "Uchida16104"
          GITHUB_EMAIL: "uho02741358@gmail.com"
        run: |
          git config --global url."https://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:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --local user.name "Uchida16104"
          git config --local user.email "uho02741358@gmail.com"
          git remote set-url origin git@github.com:Password-Maker-for-Web.git
          git add docs
          git commit -m "auto rebuilding site"
          git push origin master
